version: '3'
services:
  zookeeper:
    image: eventuateio/eventuate-zookeeper:$EVENTUATE_COMMON_VERSION
    ports:
      - 2181:2181


  kafka:
    image: eventuateio/eventuate-kafka:$EVENTUATE_KAFKA_VERSION
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
      - ZOOKEEPER_SERVERS=zookeeper:2181

  postgres:
    image: eventuateio/eventuate-postgres:$EVENTUATE_COMMON_VERSION
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: eventuate
      POSTGRES_PASSWORD: eventuate


  cdcservice:
    image: eventuateio/eventuate-cdc-service:$EVENTUATE_CDC_VERSION
    ports:
      - "8099:8080"
    depends_on:
      - postgres
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
      SPRING_DATASOURCE_USERNAME: eventuate
      SPRING_DATASOURCE_PASSWORD: eventuate
      SPRING_DATASOURCE_TEST_ON_BORROW: "true"
      SPRING_DATASOURCE_VALIDATION_QUERY: SELECT 1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      SPRING_PROFILES_ACTIVE: PostgresWal
      EVENTUATELOCAL_CDC_READER_NAME: PostgresWalReader
      EVENTUATE_CDC_TYPE: "EventuateLocal"

  mongodb:
    image: mongo:3.6
    hostname: mongodb
    command: mongod --smallfiles
    ports:
      - "27017:27017"

  customercommandside:
    build: ./customers-service/
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - kafka
      - zookeeper
    environment:
      DB_URL: jdbc:postgresql://postgres/eventuate
      DB_USERNAME: eventuate
      DB_PASSWORD: eventuate
      DB_DRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181

  orderhistoryqueryside:
    build: ./orders-history-view-service/
    ports:
      - "8082:8080"
    depends_on:
      - mongodb
      - postgres
      - kafka
      - zookeeper
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/customers_and_orders
      DB_URL: jdbc:postgresql://postgres/eventuate
      DB_USERNAME: eventuate
      DB_PASSWORD: eventuate
      DB_DRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181

  ordercommandside:
    build: ./orders-service/
    ports:
      - "8083:8080"
    depends_on:
      - postgres
      - kafka
      - zookeeper
      - customercommandside
    environment:
      CUSTOMER_SERVICE_URL: http://customercommandside:8080/customers/{customerId}
      ENDPOINTS_SENSITIVE: "false"
      DB_URL: jdbc:postgresql://postgres/eventuate
      DB_USERNAME: eventuate
      DB_PASSWORD: eventuate
      DB_DRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
