datasources:
  default:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVERCLASSNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
micronaut:
  router:
    static-resources:
      swagger-ui:
        paths: classpath:META-INF/static-content/swagger-ui
        mapping: /swagger-ui/**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**


