endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
mongodb:
  uri: ${SPRING_DATA_MONGODB_URI}
micronaut:
  router:
    static-resources:
      swagger-ui:
        paths: classpath:META-INF/static-content/swagger-ui
        mapping: /swagger-ui/**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**